[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "otp"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["srcs"]

[project.scripts]
otp = "otp:main"

[pytest]
testpaths = "tests"

